theme: jekyll-theme-minimal
title: clerouxfr's homepage
description: Bookmark this to keep an eye on my project updates!

layout: page
title: "JSON DATA"
permalink: JSON Placeholder.postman_collection.json
